
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model t1"
      columns:
          - name: id
            description: "The primary key for this table t1"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model t2"
      columns:
          - name: id
            description: "The primary key for this table t2"
            tests:
                - unique
                - not_null
